OpenNSL API Guide and Reference Manual: examples/xgs/example_led.c File Reference
example_led.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sal/driver.h>
#include <sal/pci.h>
#include <opennsl/port.h>
#include <opennsl/error.h>
#include <examples/util.h>
Data Structures
struct led_info_s
Macros
#define DEFAULT_UNIT 0
#define EXAMPLE_LED0_PROGRAM_RAM_SIZE 112
#define EXAMPLE_LED1_PROGRAM_RAM_SIZE 176
Typedefs
typedef struct led_info_s led_info_t
Functions
int main (int argc, char *argv[])
Main function for LED programming application.
Variables
char example_usage []
uint8 led0_program [EXAMPLE_LED0_PROGRAM_RAM_SIZE]
uint8 led1_program [EXAMPLE_LED1_PROGRAM_RAM_SIZE]
Macro Definition Documentation
#define DEFAULT_UNIT 0
Definition at line 37 of file example_led.c.
Referenced by main().
#define EXAMPLE_LED0_PROGRAM_RAM_SIZE 112
Definition at line 50 of file example_led.c.
Referenced by main().
#define EXAMPLE_LED1_PROGRAM_RAM_SIZE 176
Definition at line 51 of file example_led.c.
Referenced by main().
Typedef Documentation
typedef struct led_info_s led_info_t
Function Documentation
int main (int argc, char * argv[])
Main function for LED programming application.
Parameters
argc,argv commands line arguments
Returns
OPENNSL_E_XXX OpenNSL API return code
Definition at line 100 of file example_led.c.
References led_info_s::ctrl, DEFAULT_UNIT, led_info_s::dram_base, EXAMPLE_LED0_PROGRAM_RAM_SIZE, EXAMPLE_LED1_PROGRAM_RAM_SIZE, example_port_default_config(), example_read_user_choice(), example_switch_default_vlan_config(), example_usage, led0_program, led1_program, NULL, OPENNSL_CMIC_LED_DATA_RAM_SIZE, OPENNSL_CMIC_LED_PROGRAM_RAM_SIZE, OPENNSL_CMIC_LED_REG_SIZE, opennsl_driver_exit(), opennsl_driver_init(), OPENNSL_E_NONE, OPENNSL_E_PARAM, opennsl_errmsg, OPENNSL_LC_LED_ENABLE, opennsl_pci_read(), opennsl_pci_write(), and led_info_s::pram_base.
Variable Documentation
char example_usage[]
Initial value:
=
"Syntax: example_led                                                   \n\r"
"                                                                      \n\r"
"Paramaters: None                                                      \n\r"
"                                                                      \n\r"
"Example: The following command is used to run the led programming     \n\r"
" application.                                                         \n\r"
"         example_led                                                  \n\r"
"                                                                      \n\r"
Definition at line 39 of file example_led.c.
uint8 led0_program[EXAMPLE_LED0_PROGRAM_RAM_SIZE]
Initial value:
= {
      0x06,0xFE,0x80,0xD2,0x19,0x71,0x08,0xE0,0x60,0xFE,0xE9,0xD2,0x0F,0x75,0x10,0x81,
      0x61,0xFD,0x02,0x3F,0x60,0xFF,0x28,0x32,0x0F,0x87,0x67,0x4A,0x96,0xFF,0x06,0xFF,
      0xD2,0x2B,0x74,0x16,0x02,0x1F,0x60,0xFF,0x28,0x32,0x0F,0x87,0x67,0x4A,0x96,0xFF,
      0x06,0xFF,0xD2,0x13,0x74,0x28,0x02,0x0F,0x60,0xFF,0x28,0x32,0x0F,0x87,0x67,0x4A,
      0x96,0xFF,0x06,0xFF,0xD2,0x0B,0x74,0x3A,0x3A,0x48,0x32,0x07,0x32,0x08,0xC7,0x32,
      0x04,0xC7,0x97,0x71,0x57,0x77,0x69,0x32,0x00,0x32,0x01,0xB7,0x97,0x71,0x63,0x32,
      0x0E,0x77,0x6B,0x26,0xFD,0x97,0x27,0x77,0x6B,0x32,0x0F,0x87,0x57,0x00,0x00,0x00}
Definition at line 69 of file example_led.c.
Referenced by main().
uint8 led1_program[EXAMPLE_LED1_PROGRAM_RAM_SIZE]
Initial value:
= {
     0x06,0xFE,0x80,0xD2,0x19,0x71,0x08,0xE0,0x60,0xFE,0xE9,0xD2,0x0F,0x75,0x10,0x81,
     0x61,0xFD,0x02,0x20,0x67,0x89,0x02,0x24,0x67,0x89,0x02,0x10,0x67,0x89,0x02,0x28,
     0x67,0x89,0x02,0x2C,0x67,0x89,0x02,0x0C,0x67,0x89,0x02,0x2C,0x67,0x79,0x02,0x28,
     0x67,0x79,0x02,0x24,0x67,0x79,0x02,0x20,0x67,0x79,0x02,0x10,0x67,0x79,0x02,0x0C,
     0x67,0x79,0x02,0x0B,0x60,0xFF,0x28,0x32,0x0F,0x87,0x67,0x56,0x96,0xFF,0x06,0xFF,
     0xD2,0xFF,0x74,0x46,0x3A,0x36,0x32,0x07,0x32,0x08,0xC7,0x32,0x04,0xC7,0x97,0x71,
     0x63,0x77,0x75,0x32,0x00,0x32,0x01,0xB7,0x97,0x71,0x6F,0x32,0x0E,0x77,0x77,0x26,
     0xFD,0x97,0x27,0x77,0x77,0x32,0x0F,0x87,0x57,0x12,0xA0,0xF8,0x15,0x1A,0x01,0x75,
     0x85,0x28,0x67,0x56,0x57,0x32,0x0F,0x87,0x57,0x12,0xA0,0xF8,0x15,0x1A,0x01,0x71,
     0xA1,0x28,0x67,0x56,0x80,0x28,0x67,0x56,0x80,0x28,0x67,0x56,0x80,0x28,0x67,0x56,
     0x57,0x32,0x0F,0x87,0x32,0x0F,0x87,0x32,0x0F,0x87,0x32,0x0F,0x87,0x57,0x00,0x00}
Definition at line 79 of file example_led.c.
Referenced by main().